branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_bdfc680f336c_key -iv $encrypted_bdfc680f336c_iv
  -in phoenix-app-3faa3b283980.json.enc -out ../phoenix-app-3faa3b283980.json -d
services:
- docker
jobs:
  include:
  - stage: Build & Push Image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t xavierdelattre/phoenix_docker:latest .
    after_script:
    - docker push xavierdelattre/phoenix_docker:latest
  - stage: Deploy
    script:
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf "$HOME/google-cloud-sdk";
      curl https://sdk.cloud.google.com; fi
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud auth activate-service-account --keyfile=phoenix-app-3faa3b283980.json
    - gcloud compute scp docker-compose.yml phoenix-app-244815:~
