branches:
  only:
  - master
services:
- docker
jobs:
  include:
  - stage: Build & Push Image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t xavierdelattre/phoenix_docker:latest .
    after_script:
    - docker push xavierdelattre/phoenix_docker:latest
  - stage: Deploy
    before_script:
    - openssl aes-256-cbc -K $encrypted_bdfc680f336c_key -iv $encrypted_bdfc680f336c_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa
    - ssh-keyscan -H odinduclos.ovh >> ~/.ssh/known_hosts
    script:
    - rsync -r --quiet $TRAVIS_BUILD_DIR/docker-compose.yml xavier@odinduclos.ovh:/home/xavier
    - ssh xavier@odinduclos.ovh 'docker-compose -f /home/xavier/docker-compose.yml up -d '    
