# Version of docker-compose
version: '3'

services:
  phoenix:
    image: xavierdelattre/phoenix_docker:latest
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: